version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: surveydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  surveyapi:
    build:
      context: .
      dockerfile: SurveyApi/Dockerfile
    container_name: survey_api
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=surveydb;Username=admin;Password=admin123"
    ports:
      - "5000:80"

volumes:
  pgdata:
